include:
  - board: nice_nano_v2
    shield: felix_left nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: felix_right nice_view_adapter nice_view
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: felix_dongle prospector_adapter
  - board: seeeduino_xiao_ble
    shield: settings_reset